name = "Clusters"
uuid = "e544afea-a953-4249-8b17-9a4950a510ad"
authors = ["Mike Petersen <petersen@iap.fr>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Optim          = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]

[extras]

[targets]
